spring:
  config:
    activate:
      on-profile: common
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: update
    open-in-view: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  secret:
    key: ENC(m1hN8WVpNGVqyNLKW0A5DYPXix73gOpQWqxTBZuUACg8ZCPWr8WlsYoJAEP2CvAufpAigAAcIEYZW8XE3wwskICPI/H5phDcHHofN3x/7SVbw0kH6jiaqeG8mgOLpYntt8+TXq0DpnjU5tCQTm9OFIEgOnmEVFEIlkH2xKcR/O9JvduzXzcZcA==)

cloud:
  aws:
    s3:
      bucket: walkingpuppy7
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ENC(eh+u4tzJT+/Tai7jG3nv8xzHfXRI2GaUv9W1I3n3sIg=)
      secretKey: ENC(RRMyYq0UImjJej/d6jsK/SFZYTNv5YdggQlwUWK0SNB3g12pTSNI3U9FjH05Cl/LsvxjC5IgxaE=)
