spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://db-mysql.cyg0hh5az4ou.eu-west-1.rds.amazonaws.com:3306/sparta7?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: hanghae7
    driver-class-name: com.mysql.cj.jdbc.Driver
