spring:
  config:
    activate:
      on-profile: common
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: update
    open-in-view: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
        max-file-size: 10MB
        max-request-size: 10MB

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /**

jwt:
  secret:
    key: ENC(m1hN8WVpNGVqyNLKW0A5DYPXix73gOpQWqxTBZuUACg8ZCPWr8WlsYoJAEP2CvAufpAigAAcIEYZW8XE3wwskICPI/H5phDcHHofN3x/7SVbw0kH6jiaqeG8mgOLpYntt8+TXq0DpnjU5tCQTm9OFIEgOnmEVFEIlkH2xKcR/O9JvduzXzcZcA==)

cloud:
  aws:
    s3:
      bucket: walkingpuppy7
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ENC(mN6Tv57KCMbkb51e9erbI8sCI+DIoxS7WxX6gT/n2so=)
      secretKey: ENC(yjwtMBnBPx8RWMQ+j+cshQBGS61q2bu7iTS62WKj+7f9fhahmDpT3vCztEnZ2iC/ByaDk8z6+48=)
