spring:
  config:
    activate:
      on-profile: common
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: update
    open-in-view: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


jwt:
  secret:

    key: 7ZWt7ZW0OTntmZTsnbTtjIXtlZzqta3snYTrhIjrqLjshLjqs4TroZzrgpjslYTqsIDsnpDtm4zrpa3tlZzqsJzrsJzsnpDrpbzrp4zrk6TslrTqsIDsnpA=

cloud:
  aws:
    s3:
      bucket: walkingpuppy7
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: AKIAULT7JB2ZZ577R2H7
      secretKey: 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

